notify = true

hide_display_names = true

[keybindings]
"Esc" = "back"
"Ctrl+u" =  "move up 5"
"Ctrl+d" =  "move down 5"
"{" =  "move up 5"
"}" =  "move down 5"
"$" = "move up 100"
"^" = "move down 100"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%saved %duration"


